---
event_model_prior:
    dirichlet_process:
        parameters:
            concentration:
                value:      1.414216
                estimate:   false

event_time_prior:
    gamma_distribution:
        shape: 1.0
        scale: 0.01
        offset: 0.0

mcmc_settings:
    chain_length: 100000
    sample_frequency: 50

operator_settings:
    auto_optimize: true
    auto_optimize_delay: 1000
    operators:
        ModelOperator:
            weight: 3.0
            number_of_auxiliary_categories: 2
        TimeSizeRateMixer:
            weight: 3.0
            scale: 0.02
        TimeSizeRateScaler:
            weight: 0.0
            scale: 0.02
        EventTimeScaler:
            weight: 1.0
            scale: 0.02

global_comparison_settings:
    ploidy: 2
    genotypes_are_diploid: false
    markers_are_dominant: false
    population_name_delimiter: "-"
    population_name_is_prefix: true
    constant_sites_removed: false
    equal_population_sizes: false
    parameters:
        population_size:
            value: 0.002
            estimate: true
            prior:
                gamma_distribution:
                    shape: 5.0
                    scale: 0.0004
                    offset: 0.0
        root_relative_population_size:
            value: 1.0
            estimate: true
            prior:
                gamma_distribution:
                    shape: 10.0
                    scale: 0.1
                    offset: 0.0
        freq_1:
            value: 0.5
            estimate: false

        mutation_rate:
            value: 1.0
            estimate: false
    operators:
        RootPopulationSizeScaler:
            weight: 1.0
            scale: 0.05
        LeafPopulationSizeScaler:
            weight: 1.0
            scale: 0.05
        TimeRootSizeMixer:
            weight: 3.0
            scale: 0.05

comparisons:
- comparison:
    path: "../alignments/comp01-2species-10genomes-100000chars.nex"
- comparison:
    path: "../alignments/comp02-2species-10genomes-100000chars.nex"
- comparison:
    path: "../alignments/comp03-2species-10genomes-100000chars.nex"
