---
event_model_prior:
    dirichlet_process:
        parameters:
            concentration:
                value:      1.414216
                estimate:   false

event_time_prior:
    gamma_distribution:
        shape: 1.0
        scale: 0.01
        offset: 0.0

mcmc_settings:
    chain_length: 100000
    sample_frequency: 50

operator_settings:
    auto_optimize: true
    auto_optimize_delay: 10000
    operators:
        ModelOperator:
            weight: 1.0
            number_of_auxiliary_categories: 2
        CompositeHeightSizeRateMixer:
            weight: 1.0
            scale: 0.2
        ComparisonHeightScaler:
            weight: 1.0
            scale: 0.13
        PopulationSizeScaler:
            weight: 1.0
            scale: 0.4
        PopulationSizeMultiplierMixer:
            weight: 1.0
            scale: 0.2

global_comparison_settings:
    ploidy: 2
    genotypes_are_diploid: false
    markers_are_dominant: false
    population_name_delimiter: "-"
    population_name_is_prefix: true
    constant_sites_removed: false
    parameters:
        population_size:
            value: 0.002
            estimate: true
            prior:
                gamma_distribution:
                    shape: 4.0
                    scale: 0.0005
                    offset: 0.0
        population_size_multipliers:
            value: [1.0, 1.0, 1.0]
            estimate: true
            prior:
                dirichlet_distribution:
                    alpha: [10.0, 10.0, 10.0]
        freq_1:
            value: 0.5
            estimate: false

        mutation_rate:
            value: 1.0
            estimate: false


comparisons:
- comparison:
    path: "../alignments/comp01-2species-10genomes-500000chars.nex"
- comparison:
    path: "../alignments/comp02-2species-10genomes-500000chars.nex"
- comparison:
    path: "../alignments/comp03-2species-10genomes-500000chars.nex"
